In [15]:
import pandas as pd
df = pd.read_csv('nyc_weather.csv')
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [4]:
df.set_index('EST' , inplace=True)

In [5]:
df

,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
EST,,,,,,,,,,
1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [6]:
df.loc['1/3/2016']

Temperature                40
DewPoint                   21
Humidity                   47
Sea Level PressureIn    29.86
VisibilityMiles            10
WindSpeedMPH              8.0
PrecipitationIn             0
CloudCover                  1
Events                    NaN
WindDirDegrees            277
Name: 1/3/2016, dtype: object

In [12]:
df.reset_index(inplace=True)
df

,level_0,index,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,0,0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1,1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,2,2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,3,3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,4,4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,5,5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,6,6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,7,7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,8,8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,9,9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,10,10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,11,11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,12,12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,13,13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,14,14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,15,15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,16,16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,17,17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,18,18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,19,19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,20,20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,21,21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,22,22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,23,23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,24,24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,25,25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,26,26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,27,27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,28,28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,29,29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,30,30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [8]:
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [16]:
df.set_index('events',inplace=True)
df

KeyError: "None of ['events'] are in the columns"

In [17]:
df.columns

Index(['EST', 'Temperature', 'DewPoint', 'Humidity', 'Sea Level PressureIn',
       'VisibilityMiles', 'WindSpeedMPH', 'PrecipitationIn', 'CloudCover',
       'Events', 'WindDirDegrees'],
      dtype='str')

In [18]:
df.set_index('Events', inplace=True)
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,WindDirDegrees
Events,,,,,,,,,,
NaN,1/1/2016,38,23,52,30.03,10,8.0,0,5,281
NaN,1/2/2016,36,18,46,30.02,10,7.0,0,3,275
NaN,1/3/2016,40,21,47,29.86,10,8.0,0,1,277
NaN,1/4/2016,25,9,44,30.05,10,9.0,0,3,345
NaN,1/5/2016,20,-3,41,30.57,10,5.0,0,0,333
NaN,1/6/2016,33,4,35,30.50,10,4.0,0,0,259
NaN,1/7/2016,39,11,33,30.28,10,2.0,0,3,293
NaN,1/8/2016,39,29,64,30.20,10,4.0,0,8,79
Rain,1/9/2016,44,38,77,30.16,9,8.0,T,8,76
Rain,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,109
NaN,1/11/2016,33,8,37,29.92,10,NaN,0,1,289
NaN,1/12/2016,35,15,53,29.85,10,6.0,T,4,235
NaN,1/13/2016,26,4,42,29.94,10,10.0,0,0,284
NaN,1/14/2016,30,12,47,29.95,10,5.0,T,7,266
NaN,1/15/2016,43,31,62,29.82,9,5.0,T,2,101
Rain,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,340
Fog-Snow,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,345
Snow,1/18/2016,25,6,53,29.83,9,12.0,T,2,293
NaN,1/19/2016,22,3,42,30.03,10,11.0,0,1,293
NaN,1/20/2016,32,15,49,30.13,10,6.0,0,2,302
NaN,1/21/2016,31,11,45,30.15,10,6.0,0,1,312
Snow,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,34
Fog-Snow,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,42
Snow,1/24/2016,28,11,53,29.92,8,6.0,T,3,327
NaN,1/25/2016,34,18,54,30.25,10,3.0,0,2,286
NaN,1/26/2016,43,29,56,30.03,10,7.0,0,2,244
Rain,1/27/2016,41,22,45,30.03,10,7.0,T,3,311
NaN,1/28/2016,37,20,51,29.90,10,5.0,0,1,234
NaN,1/29/2016,36,21,50,29.58,10,8.0,0,4,298
NaN,1/30/2016,34,16,46,30.01,10,7.0,0,0,257
NaN,1/31/2016,46,28,52,29.90,10,5.0,0,0,241

In [19]:
df.loc['Snow']

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,WindDirDegrees
Events,,,,,,,,,,
Snow,1/18/2016,25,6,53,29.83,9,12.0,T,2,293
Snow,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,34
Snow,1/24/2016,28,11,53,29.92,8,6.0,T,3,327