In [1]:
import pandas as pd
india_weather = pd.DataFrame({
    "city":['mumbai','delhi','bangalore'],
    "temperature":[32,45,30],
    "humidity":[80,60,78]
})
india_weather

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [2]:
import pandas as pd
us_weather = pd.DataFrame({
    "city":['new york','chicago','orlando'],
    "temperature":[21,12,35],
    "humidity":[68,65,75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           12        65
2   orlando           35        75

In [3]:
#join this 2 
df = pd.concat([india_weather, us_weather])
df
#u can see the indexes are same

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
0   new york           21        68
1    chicago           12        65
2    orlando           35        75

In [4]:
#to make index series
df = pd.concat([india_weather, us_weather],ignore_index=True)
df

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78
3   new york           21        68
4    chicago           12        65
5    orlando           35        75

In [5]:
#you can also pass keys
#to make index series
df = pd.concat([india_weather, us_weather],keys=['india','us'])
df

              city  temperature  humidity
india 0     mumbai           32        80
      1      delhi           45        60
      2  bangalore           30        78
us    0   new york           21        68
      1    chicago           12        65
      2    orlando           35        75

In [6]:
#if you want to retrieve specific country weather
df.loc['india']

        city  temperature  humidity
0     mumbai           32        80
1      delhi           45        60
2  bangalore           30        78

In [7]:
df.loc['us']

       city  temperature  humidity
0  new york           21        68
1   chicago           12        65
2   orlando           35        75

In [8]:

temperature_df = pd.DataFrame({
    "city":['mumbai','delhi','banglore'],
    "temperature":[32,40,30],
})
temperature_df

       city  temperature
0    mumbai           32
1     delhi           40
2  banglore           30

In [9]:
windspeed_df = pd.DataFrame({
    "city":['mumbai','delhi','banglore'],
    "windspeed":[7,12,9],
})
windspeed_df

       city  windspeed
0    mumbai          7
1     delhi         12
2  banglore          9

In [10]:
df = pd.concat([temperature_df, windspeed_df])
df
#it is creating additional rows windspeed should appear as column

       city  temperature  windspeed
0    mumbai         32.0        NaN
1     delhi         40.0        NaN
2  banglore         30.0        NaN
0    mumbai          NaN        7.0
1     delhi          NaN       12.0
2  banglore          NaN        9.0

In [11]:
#axis=0 -->append second Dataframe as rows
#axis=1 -->append second dataframe as columns
df = pd.concat([temperature_df, windspeed_df],axis=1)
df

       city  temperature      city  windspeed
0    mumbai           32    mumbai          7
1     delhi           40     delhi         12
2  banglore           30  banglore          9

In [12]:
temperature_df = pd.DataFrame({
    "city":['mumbai','delhi','banglore'],
    "temperature":[32,40,30],
},index=[0,1,2])
temperature_df

       city  temperature
0    mumbai           32
1     delhi           40
2  banglore           30

In [15]:
#if you missing any value or inter changed values it will execute wrong data so to avoid that use index
windspeed_df = pd.DataFrame({
    "city":['delhi','mumbai'],
    "windspeed":[12,7],
},index=[1,0])
windspeed_df

     city  windspeed
1   delhi         12
0  mumbai          7

In [16]:
df = pd.concat([temperature_df, windspeed_df],axis=1)
df

       city  temperature    city  windspeed
0    mumbai           32  mumbai        7.0
1     delhi           40   delhi       12.0
2  banglore           30     NaN        NaN

In [18]:
#join dataframe with series

s=pd.Series(['Humid','Dry','Rain'],name='event')
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: str

In [20]:
#append this series to temperature_df dataframe
df=pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0    mumbai           32  Humid
1     delhi           40    Dry
2  banglore           30   Rain