In [1]:
import pandas as pd

df = pd.read_csv('weather_data.csv')
df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  02/01/2017           35          7  Sunny
2  03/01/2017           28          2   Snow

In [8]:
import pandas as pd

df = pd.read_excel('weather_data.xlsx')
df

          day  temperature  windspeed  event
0  01/01/2017           32          6   Rain
1  02/01/2017           35          7  Sunny
2  03/01/2017           28          2   Snow

In [9]:
import openpyxl
print(openpyxl.__version__)

3.1.5

In [11]:
weather_data={
    'day':['1/1/2017','1/2/2017','1/3/2017'],
    'temperature':[32,35,28],
    'windspeed':[6,7,2],
    'event':['Rain','Sunny','Snow']
}
df=pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [13]:
weather_data=[
    ('1/1/2017',32,6,'Rain'),
    ('1/2/2017',35,7,'Sunny'),
    ('1/3/2017',28,2,'Snow')
]
df = pd.DataFrame(weather_data, columns =['day','temperature','windspeed','event'])
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow

In [14]:
weather_data=[
    {'day':'1/2/2017','temperature':32,'windspeed':6,'event':'Rain'},
    {'day':'1/2/2017','temperature':35,'windspeed':7,'event':'Sunny'},
    {'day':'1/2/2017','temperature':28,'windspeed':2,'event':'Snow'}
]
df=pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/2/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/2/2017           28          2   Snow