In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('weather_data (1).csv')
df

        day  temperature  windspeed     event
0  1/1/2017           32          6      Rain
1  1/2/2017       -99999          7     Sunny
2  1/3/2017           28     -99999      Snow
3  1/4/2017       -99999          7  No Event
4  1/5/2017           32     -99999      Rain
5  1/6/2017           31          2     Sunny

In [6]:
#replacing special values (-99999)
new_df = df.replace(-99999,np.nan)
new_df

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  No Event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny

In [4]:
import numpy as np
print(np.__version__)

2.5.4

In [8]:
#what if we have -88888
#Replace values based on specific columns
new_df = df.replace({
         'temperature': -99999,
         'windspeed': -99999,
         'event': '0'
},np.nan)
new_df

        day  temperature  windspeed     event
0  1/1/2017         32.0        6.0      Rain
1  1/2/2017          NaN        7.0     Sunny
2  1/3/2017         28.0        NaN      Snow
3  1/4/2017          NaN        7.0  No Event
4  1/5/2017         32.0        NaN      Rain
5  1/6/2017         31.0        2.0     Sunny

In [10]:
#i want to replace temp and windspeed with nan and event with Sunny
new_df = df.replace({
    -99999: np.nan,
    'No Event': 'Sunny'
        })
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny

In [12]:
#weather_data (3).csv --> having Unit of measure
import pandas as pd
import numpy as np
df = pd.read_csv('weather_data (3).csv')
df

          day temperature windspeed     event
0  01-01-2017         32F      6mph      Rain
1  01-02-2017      -99999      7mph     Sunny
2  01-03-2017          28    -99999      Snow
3  01-04-2017      -99999         7  No Event
4  01-05-2017          32    -99999      Rain
5  01-06-2017          31         2     Sunny

In [15]:
#you want cut of this measure val
#regex (Regular Expression) is commonly used for searching, matching, and replacing text patterns.
new_df = df.replace({
    'temperature': '[A-Za-z]',
    'windspeed': '[A-Za-z]',
},'',regex=True)
new_df

          day temperature windspeed     event
0  01-01-2017          32         6      Rain
1  01-02-2017      -99999         7     Sunny
2  01-03-2017          28    -99999      Snow
3  01-04-2017      -99999         7  No Event
4  01-05-2017          32    -99999      Rain
5  01-06-2017          31         2     Sunny

In [16]:
df = pd.DataFrame({
    'score': ['exceptional', 'average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})

df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [17]:
#now ypu want to replace score with numbers 
new_df = df.replace(
    ['poor', 'average', 'good', 'exceptional'],
    [1, 2, 3, 4]
)
new_df

  score  student
0     4      rob
1     2     maya
2     3  parthiv
3     1      tom
4     2   julian
5     4    erica