In [2]:
import pandas as pd
df = pd.read_csv("weather_data (2).csv")
df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        9.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08          NaN        NaN   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [6]:
#interpolate() is used to fill missing values (NaN) by estimating values from existing data instead of using a fixed value like 0 or the column average.
new_df=df.fillna(0)
new_df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          0.0        9.0   Sunny
2  2017-01-05         28.0        0.0    Snow
3  2017-01-06          0.0        7.0       0
4  2017-01-07         32.0        0.0    Rain
5  2017-01-08          0.0        0.0   Sunny
6  2017-01-09          0.0        0.0       0
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [7]:
new_df.dtypes

day                str
temperature    float64
windspeed      float64
event           object
dtype: object

In [12]:
#interpolate() is used to fill missing values (NaN) by estimating values from existing data instead of using a fixed value like 0 or the column average.
new_df = df.copy() #Create a copy df      -> Original and  new_df  -> Copy

new_df['day'] = pd.to_datetime(new_df['day']) #Convert string dates to datetime

new_df.set_index('day', inplace=True) #Make day the index, Because method='time' uses the dates in the index to calculate missing values. 

#Select the columns
new_df[['temperature', 'windspeed']] = (
    new_df[['temperature', 'windspeed']].interpolate(method='time') #Apply interpolation
)

new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

In [13]:
#it can be written also like this.
new_df = df.copy() 
new_df['day'] = pd.to_datetime(new_df['day'])
new_df.set_index('day', inplace=True)
new_df['temperature'] = new_df['temperature'].interpolate(method='time')
new_df['windspeed'] = new_df['windspeed'].interpolate(method='time')
new_df

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny