In [2]:
import pandas as pd
df = pd.read_csv("weather_data (2).csv")
df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        9.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08          NaN        NaN   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [4]:
#dropna() is used to remove rows or columns that contain missing values (NaN).
new_df = df.dropna()
new_df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [5]:
#Drop a row (or column) only if ALL values are NaN.
new_df = df.dropna(how='all')
new_df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        9.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08          NaN        NaN   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [6]:
#thresh means minimum number of non-NaN values required to keep a row (or column).
#Drop a row (or column) only if ALL values are NaN.
new_df = df.dropna(thresh=1)#min 1 valid values
new_df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        9.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08          NaN        NaN   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [8]:
new_df = df.dropna(thresh=3)#min 1 valid values
new_df

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        9.0   Sunny
2  2017-01-05         28.0        NaN    Snow
4  2017-01-07         32.0        NaN    Rain
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0   Sunny

In [10]:
#insert missing date
#reindex() → Insert missing dates and fill their values with NaN
#date_range() → creates all dates between start and end.
new_df = df.copy() #Create a copy

new_df['day'] = pd.to_datetime(new_df['day']) #Convert day to datetime

new_df = new_df.set_index('day') #Make day the index

new_df = new_df.reindex(
    pd.date_range(
        start='2017-01-01',
        end='2017-01-10'
    ) #Create all dates from Jan 1 to Jan 10
)

new_df

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy