In [1]:
import pandas as pd
df= pd.read_csv('weather_data (4).csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [7]:
#pivot table is used to transform and summarize data, making it easier to analyze relationships between columns.
df.pivot(index='date',columns='city')

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [8]:
#if u want only specific columns
df.pivot(index='date',columns='city', values='humidity')

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [9]:
df.pivot(index='humidity',columns='city')

              date                     temperature
city       beijing    mumbai  new york     beijing mumbai new york
humidity
26        5/1/2017       NaN       NaN        80.0    NaN      NaN
30        5/2/2017       NaN       NaN        77.0    NaN      NaN
35        5/3/2017       NaN       NaN        79.0    NaN      NaN
56             NaN       NaN  5/1/2017         NaN    NaN     65.0
58             NaN       NaN  5/2/2017         NaN    NaN     66.0
60             NaN       NaN  5/3/2017         NaN    NaN     68.0
80             NaN  5/1/2017       NaN         NaN   75.0      NaN
83             NaN  5/2/2017       NaN         NaN   78.0      NaN
85             NaN  5/3/2017       NaN         NaN   82.0      NaN

In [10]:
import pandas as pd
df=pd.read_csv('weather_data (5).csv')
df
#same day 2 diff temp and humid

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [12]:
#create average temp and humid
#pivot() = No duplicates allowed.
#pivot_table() = Duplicates allowed, aggregates values.

df.pivot_table(index='city', columns='date')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [13]:
df.pivot_table(index='city', columns='date',aggfunc='sum')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai        163      111         153      162
new york      110      122         126      142

In [14]:
#margins=True adds totals (Grand Total) rows and/or columns to a pivot table.
#margins_name='Total' → changes the label from All to Total.
df.pivot_table(index='city', columns='date',margins=True)

         humidity                 temperature
date     5/1/2017 5/2/2017    All    5/1/2017 5/2/2017     All
city
mumbai      81.50    55.50  68.50       76.50     81.0  78.750
new york    55.00    61.00  58.00       63.00     71.0  67.000
All         68.25    58.25  63.25       69.75     76.0  72.875

In [15]:

df=pd.read_csv('weather_data (5).csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [19]:
#avg tem month may and desc
#pd.Grouper() is used with groupby() or pivot_table() to group datetime data into time periods such as days, months, quarters, or years.
import pandas as pd

df = pd.read_csv("weather_data (5).csv")

df['date'] = pd.to_datetime(df['date'])

df.pivot_table(
    index=pd.Grouper(key='date', freq='ME'),
    columns='city'
)

           humidity          temperature
city         mumbai new york      mumbai new york
date
2017-05-31     68.5     58.0       78.75     67.0